"""
Vocabulary and character set inspector.

Read-only view over the base language profiles in config/language_profiles.py.

The effective character set for a language lives in version control
(config/language_profiles.py). To change it, edit that file and open a pull
request — there is no runtime-mutable overlay. A training character set
determines the CTC output layer; one stray character silently scrambles the
model's output with no error raised, so changes go through the same review as
any other code change.

Usage:
    mgr = VocabManager("efi")
    result = mgr.test_text("ʌkɔ mme eka")
    print(mgr.export_reference())
"""

from __future__ import annotations

import unicodedata
from pathlib import Path
from typing import FrozenSet

from config.language_profiles import get_profile


# ---------------------------------------------------------------------------
# VocabManager
# ---------------------------------------------------------------------------

class VocabManager:
    """
    Read-only view of the effective character set for one language, as
    defined by its committed profile in config/language_profiles.py.
    """

    def __init__(self, language_code: str):
        self.language_code = language_code
        self._base = get_profile(language_code)

    # ── Effective character sets ───────────────────────────────────────────

    @property
    def effective_base_chars(self) -> FrozenSet[str]:
        return self._base.base_chars

    @property
    def effective_combining(self) -> FrozenSet[str]:
        return self._base.extra_combining

    def is_char_allowed(self, char: str) -> bool:
        cat = unicodedata.category(char)
        if cat == "Mn":
            return char in self.effective_combining
        return char in self.effective_base_chars or char in self._base.punctuation

    # ── Inspection ────────────────────────────────────────────────────────

    def test_text(self, text: str) -> dict:
        """Test whether a text string is valid under the committed profile."""
        normalized = unicodedata.normalize("NFC", text).strip()
        illegal: list[dict] = []
        for char in normalized:
            if not self.is_char_allowed(char):
                illegal.append({
                    "char": char,
                    "codepoint": f"U+{ord(char):04X}",
                    "unicode_name": unicodedata.name(char, "UNKNOWN"),
                })
        return {
            "is_valid": len(illegal) == 0,
            "normalized_text": normalized,
            "illegal_chars": illegal,
            "language": self.language_code,
        }

    def list_chars(self) -> dict:
        """Return the full effective character inventory."""

        def _describe(chars: FrozenSet[str]) -> list[dict]:
            return [
                {
                    "char":         c,
                    "codepoint":    f"U+{ord(c):04X}",
                    "unicode_name": unicodedata.name(c, "UNKNOWN"),
                }
                for c in sorted(chars, key=lambda ch: ord(ch))
            ]

        return {
            "language":        self.language_code,
            "language_name":   self._base.name,
            "base_chars":      _describe(self.effective_base_chars),
            "combining_marks": _describe(self.effective_combining),
            "punctuation":     sorted(self._base.punctuation),
            "total_base":      len(self.effective_base_chars),
        }

    def export_reference(self, output_path: str | None = None) -> dict:
        """
        Export the effective character inventory as a human-readable Markdown
        reference document. Useful for sharing with linguists for sign-off.

        Args:
            output_path: Where to save the .md file. If None, saves to
                         data/vocab/<lang>_reference.md
        """
        inv = self.list_chars()
        lang_name = inv["language_name"]
        lang_code = inv["language"]

        lines = [
            f"# {lang_name} ({lang_code}) — Character Reference",
            "",
            f"Generated by IdemAI Vocab Manager.  Total base chars: {inv['total_base']}",
            "",
            "---",
            "",
            "## Base Characters",
            "",
            "| Char | Codepoint | Unicode Name |",
            "|------|-----------|--------------|",
        ]
        for c in inv["base_chars"]:
            lines.append(f"| `{c['char']}` | {c['codepoint']} | {c['unicode_name']} |")

        lines += [
            "",
            "## Combining Marks (Tone Marks)",
            "",
            "| Mark | Codepoint | Unicode Name |",
            "|------|-----------|--------------|",
        ]
        for c in inv["combining_marks"]:
            lines.append(f"| `{c['char']}` | {c['codepoint']} | {c['unicode_name']} |")

        lines += [
            "",
            "## Allowed Punctuation",
            "",
            "```",
            " ".join(repr(p) for p in inv["punctuation"]),
            "```",
            "",
            "---",
            "*Share this document with a native speaker or linguist for sign-off before recording begins.*",
        ]

        content = "\n".join(lines)

        if output_path is None:
            output_path = str(Path(__file__).resolve().parent.parent / "data" / "vocab" / f"{lang_code}_reference.md")

        Path(output_path).parent.mkdir(parents=True, exist_ok=True)
        Path(output_path).write_text(content, encoding="utf-8")

        return {
            "exported_to": output_path,
            "language":    lang_code,
            "total_chars": inv["total_base"],
        }


# ---------------------------------------------------------------------------
# Convenience: get a manager by language code
# ---------------------------------------------------------------------------

def get_manager(language_code: str) -> VocabManager:
    return VocabManager(language_code)
